version: '2.1'
services:
  keycloak:
    image: jboss/keycloak:9.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_USER=admin
      - KEYCLOAK_PASSWORD=admin
      - DB_VENDOR=H2
      - SERVER_CONFIG=standalone.xml
    expose:
      - 8080
    command:
      - "-b 0.0.0.0"
      - "-Dkeycloak.import=/opt/jboss/keycloak/kibana-realm.json"
    ports:
      - "8080:8080"
    volumes:
      - ./env/keycloak/kibana-realm.json:/opt/jboss/keycloak/kibana-realm.json

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.5.0
    container_name: elasticsearch
    environment:
      ES_JAVA_OPTS: -Xms1g -Xmx1g
      discovery.type: single-node
    ports:
      - "9200:9200"

  kibana:
    image: docker.elastic.co/kibana/kibana:7.5.0
    container_name: kibana
    ports:
      - 5603:5603
    restart: always
    volumes:
      - ./env/kibana/kibana.yml:/opt/kibana/config/kibana.yml

  cerebro:
    image: lmenezes/cerebro:latest
    container_name: cerebro
    restart: always
    ports:
      - "9000:9000"
